server:
  port: 8811
terminus:
  localdebug:
    enable: true
    local: true
    http-port: 8710
    tunnel-port: 7000

logging:
  level:
    io.rsocket.FrameLogger: DEBUG


spring:
  application:
    name: helloApplication
