server:
  port: 8810


terminus:
  localdebug:
    enable: true
    local: false
    http-port: 8710
    tunnel-port: 7000

logging:
  level:
    io.rsocket.FrameLogger: DEBUG
spring:
  application:
    name: helloApplication
